// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcruffumlcxllxremoum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjcnVmZnVtbGN4bGx4cmVtb3VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY3MTY0MTIsImV4cCI6MjA1MjI5MjQxMn0.pOiELnx4ec0U7iRa4Z8ivfqX5dVqaiUlAjtht2kn8Zs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);